version: '3'

networks:

  backend-network:
    driver: bridge

services:

  client_mobile:
    build: ./client_mobile
    volumes:
      - common-volume:/shared

  client_web:
    depends_on:
      - client_mobile
      - server
    build: ./web_client
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    networks:
      - backend-network
    volumes:
      - common-volume:/shared

  server:
    depends_on:
      - client_mobile
      - db
    build: ./server
    ports:
      - 8080:8080
    restart: always
    networks:
      - backend-network
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - common-volume:/shared

  db:
    image: elasticsearch:7.5.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - backend-network
    ports:
      - 9200:9200
    volumes:
      - ./server/db:/data/db
    restart: always
    #logging:
     # driver: none

volumes:
  common-volume:
